using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using POS_System.Business.Utils;
using POS_System.Data.Database;
using POS_System.Data.Identity;
using POS_System.IntegrationTests.Helpers;
using System.Net.Http.Headers;

namespace POS_System.IntegrationTests;

public class PosSystemApiFactory : WebApplicationFactory<Program>
{
    // Each factory instance gets its own isolated in-memory database and temp file
    private readonly string _dbName = Guid.NewGuid().ToString();
    private readonly string _businessDetailsFileName = $"test-bd-{Guid.NewGuid()}.json";

    public string BusinessDetailsFilePath =>
        Path.Combine(Path.GetTempPath(), _businessDetailsFileName);

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureAppConfiguration((_, config) =>
        {
            var testConfig = new Dictionary<string, string?>
            {
                // JWT - must match what DependencyInjection.TryGetConfigValue reads
                ["POSJwtSecretKey"] = JwtTokenHelper.SecretKey,
                ["POSIssuer"] = JwtTokenHelper.Issuer,
                ["POSAudience"] = JwtTokenHelper.Audience,

                // Stripe (required by StripeConfiguration, CouponService uses it at runtime)
                ["Stripe:SecretKey"] = "sk_test_fake_key_for_integration_tests",

                // Email (required by EmailConfiguration binding)
                ["EmailConfiguration:From"] = "test@test.com",
                ["EmailConfiguration:SmtpServer"] = "localhost",
                ["EmailConfiguration:Port"] = "25",
                ["EmailConfiguration:UserName"] = "test",
                ["EmailConfiguration:Password"] = "test",

                // AWS SNS (SmsService catches all exceptions, so fake values are fine)
                ["AWS:AccessKeyId"] = "fakeAccessKeyId",
                ["AWS:SecretAccessKey"] = "fakeSecretAccessKey",
                ["AWS:SessionToken"] = "fakeSessionToken",
                ["AWS:Region"] = "eu-north-1",

                // Business details file storage (uses temp directory)
                ["BusinessDetails:RelativePath"] = Path.GetTempPath(),
                ["BusinessDetails:FileName"] = _businessDetailsFileName,

                // Database connection string (replaced with InMemory, but required to avoid null)
                ["ConnectionStrings:LocalConnection"] = "Host=localhost;Database=testdb;",

                // Suppress file logging in tests
                ["FileProvider:Events:Path"] = Path.Combine(Path.GetTempPath(), "test-events.log"),
                ["FileProvider:Exceptions:Path"] = Path.Combine(Path.GetTempPath(), "test-exceptions.log"),
                ["FileProvider:Events:FileCreationInterval"] = "12:00:00",
                ["FileProvider:Exceptions:FileCreationInterval"] = "24:00:00",
            };

            config.AddInMemoryCollection(testConfig);
        });

        builder.ConfigureServices(services =>
        {
            // Replace PostgreSQL DbContext with InMemory
            var dbDescriptor = services.SingleOrDefault(
                d => d.ServiceType == typeof(DbContextOptions<ApplicationDbContext>));
            if (dbDescriptor != null)
                services.Remove(dbDescriptor);

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseInMemoryDatabase(_dbName));

            // Replace SMTP email sender with a no-op to prevent real emails
            var emailDescriptor = services.SingleOrDefault(
                d => d.ServiceType == typeof(IEmailSender));
            if (emailDescriptor != null)
                services.Remove(emailDescriptor);

            services.AddScoped<IEmailSender, NoOpEmailSender>();

            // Override JWT validation parameters so that tokens generated by
            // JwtTokenHelper are accepted regardless of what appsettings.Development.json
            // contains (PostConfigure runs after AddJwtBearer, so it wins).
            services.PostConfigure<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme, options =>
            {
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true,
                    ValidateAudience = true,
                    ValidateLifetime = true,
                    ValidateIssuerSigningKey = true,
                    ValidIssuer = JwtTokenHelper.Issuer,
                    ValidAudience = JwtTokenHelper.Audience,
                    IssuerSigningKey = new SymmetricSecurityKey(
                        Encoding.UTF8.GetBytes(JwtTokenHelper.SecretKey))
                };
            });
        });
    }

    // Returns an unauthenticated client
    public HttpClient CreateAnonymousClient() => CreateClient();

    // Returns a client with a Bearer JWT containing the specified claims
    public HttpClient CreateClientWithClaims(params string[] claims)
    {
        var client = CreateClient();
        client.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", JwtTokenHelper.GenerateToken(claims));
        return client;
    }

    // Returns a client with all available permission claims
    public HttpClient CreateFullAccessClient() =>
        CreateClientWithClaims(JwtTokenHelper.AllClaims);

    // Resets the database to its seeded state and seeds Identity roles
    // Call from InitializeAsync in each test class to guarantee full isolation
    public async Task ResetDatabaseAsync()
    {
        using var scope = Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        await db.Database.EnsureDeletedAsync();
        await db.Database.EnsureCreatedAsync();

        // Seed the Identity roles that AuthService.GetRoleById maps to
        var roleManager = scope.ServiceProvider
            .GetRequiredService<Microsoft.AspNetCore.Identity.RoleManager<ApplicationRole>>();

        string[] roleNames = ["None", "Service provider", "Cashier", "Owner", "Super admin"];
        foreach (var roleName in roleNames)
        {
            if (!await roleManager.RoleExistsAsync(roleName))
                await roleManager.CreateAsync(new ApplicationRole { Name = roleName });
        }

        // Clean up any leftover business-details temp file from a previous run
        if (File.Exists(BusinessDetailsFilePath))
            File.Delete(BusinessDetailsFilePath);
    }
}
